### PR TITLE
refactor: install sc proxy using actions/tool-cache instead of docker 

### PR DESCRIPTION
**Pull request by ZauberNerd**
This commit refactors the sauce-connect-action to use the
@actions/tool-cache to download the sauce connect proxy binary for the
current architecture and place it into the hosted tool cache.

This allows to use the action inside containers, for example by using
the `container` directive or even inside the `act` tool.

References:
* https://github.com/actions/toolkit/tree/main/packages/tool-cache
* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer
* https://github.com/nektos/act

### CODE REVIEW

**Comment by ZauberNerd** [comment]
@waggledans any thoughts on this change?

**Comment by waggledans** [comment]
@ZauberNerd tnx for your contribution.  Looks promising, will review as soon as I have time (probably tomorrow)

**Comment by ZauberNerd** [comment]
@waggledans did you find some time to take a look at this change?

**Comment by waggledans** [comment]
Merged https://github.com/saucelabs/sauce-connect-action/pull/53, will check this one tomorrow. Thank you for your contribution!

**Comment by waggledans** [comment]
The [CI](https://github.com/saucelabs/sauce-connect-action/actions/runs/3042533268/jobs/4900977585) fails with

```
/opt/hostedtoolcache/sc/4.8.1/x64/sc-4.8.1-linux/bin/sc  ... --readyfile=/tmp/sauce-connect-actioncO0LVR/sc.ready

....

Sauce connect log:

2022-09-13 05:38:55.259 [1689] [CLI] [info] Sauce Connect 4.8.1, build ...
22-09-13 05:38:55.259 [1689] [CLI] [fatal] Error creating pidfile /srv/sauce-connect.pid: open /srv/sauce-connect.pid: permission denied
```

**Comment by ZauberNerd** [comment]
As per my last commit: I don't think the pidfile is used at all, because the [documentation](https://docs.saucelabs.com/dev/cli/sauce-connect-proxy/#--pidfile) notes, that the `--pidfile` argument is used to automatically stop the sauce connect proxy.
But we are using [`saveState()`](https://github.com/ZauberNerd/sauce-connect-action/blob/e04ab85d23eaa993948bae225dc75ec201b88809/src/main.ts#L17) and [`getState()`](https://github.com/ZauberNerd/sauce-connect-action/blob/e04ab85d23eaa993948bae225dc75ec201b88809/src/post.ts#L5) to pass the pid between the main and post action and thus won't need the pid file.

**Comment by waggledans** [comment]
lgtm.  Thank you @ZauberNerd !

**Review by waggledans — APPROVED** [review]

**Pull request merged**
