### PR TITLE
Bump base image to 4.6.2 from 4.5.4

### PR DESCRIPTION
**Pull request by token-cjg**
This should close issue #3

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Awesome, thanks!

**Comment by shoukoo** [comment]
@token-cjg  @christian-bromann  Do you need to create the saucelabs/sauce-connect:4.6.2 image? It doesn't exist atm.

**Comment by token-cjg** [comment]
Thanks for the heads up regarding this @shoukoo; I see [that the latest image here is 4.5.4](https://hub.docker.com/r/saucelabs/sauce-connect/tags), I guess I just took issue #3 at face value and assumed that image 4.6.2 had already been built, without doing proper due diligence.

In that case then I'll raise a revert request on this ... unless of course @christian-bromann if you might be able to work with your team to build an image for the relevant tag instead?

**Comment by christian-bromann** [comment]
I will push the image to DockerHub.

**Pull request merged**
