### PR TITLE
Fix `accesskey` to `accessKey`

### PR DESCRIPTION
**Pull request by petamoriken**
It works without this fix, but the validation does not pass.

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Thank you, this is more consistent. 👍

**Comment by petamoriken** [comment]
@christian-bromann Sorry, that was poorly worded; the GitHub Actions parameters are not case sensitive, so it wasn't a breaking change.

It seems you forget to release the `v2` tag, so please do 😄

**Comment by christian-bromann** [comment]
The release tag is right here: https://github.com/saucelabs/sauce-connect-action/releases/tag/v2.0.0

> Sorry, that was poorly worded; the GitHub Actions parameters are not case sensitive, so it wasn't a breaking change.

Ah ok, didn't know that. Not a problem.

**Comment by petamoriken** [comment]
I'm assuming that `v2` refers to the same commit as `v2.0.0`, just as `v1` refers to the same commit as `v1.1.3`. If not, it seems that writing `saucelabs/sauce-connect-action@v2` in the Yaml file would not work.

**Pull request merged**
